First = input("First => ")
print(First)
Second = input("Second => ")
print(Second)
print("Example variable names\n" + "Lower case:", First.lower() + "_" + Second.lower(), len(First + "_" + Second))
print("For constants:", First.upper() + "_" + Second.upper(), len(First + "_" + Second))
print("Camel case:", First.title() + Second.title(), len(First + Second))
print("System variables:", "_" + First.lower() + "_" + Second.lower(), len("_" + First.lower() + "_" + Second.lower()))
print("Silly variable:", ((First.lower() + "_" + Second.lower()).replace("o","_")).replace("l", "_"))