Radius_of_Sun = float(input("Enter the radius of the Sun (miles) -> "))
print(round(Radius_of_Sun))
Radius_of_Moon = float(input("Enter the radius of the Moon (miles) -> "))
print(round(Radius_of_Moon))
Distance_Sun_to_Earth = float(input("Enter the maximum distance to the Sun (miles) -> "))
print(round(Distance_Sun_to_Earth))
Distance_from_Moon = float(input("Enter the minimum distance to the Moon (miles) -> "))
print(round(Distance_from_Moon))
Rate = float(input("Enter the rate the Moon is moving away (in/year) -> "))
print(Rate)
Distance_Moon_to_Earth = Distance_Sun_to_Earth * (Radius_of_Moon / Radius_of_Sun)
print("The Moon will have exactly the same apparent size as the Sun when it is {0:.2f}".format(Distance_Moon_to_Earth), "miles away.")
Moon_Recede = Distance_Moon_to_Earth - Distance_from_Moon
print("The Moon will need to recede another {0:.2f} miles".format(Moon_Recede))
print("Which will occur in", round(Moon_Recede / ((Rate / 12) / 5280)), "years at the current rate.")